// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfUeeRH-ZUIdtMJXwhrSamdYYtjVLVnc8',
    appId: '1:141920116298:web:eed634fc2b37f54fa3d0b3',
    messagingSenderId: '141920116298',
    projectId: 'growable-b7814',
    authDomain: 'growable-b7814.firebaseapp.com',
    storageBucket: 'growable-b7814.appspot.com',
    measurementId: 'G-1130ZPTNN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEJp2t05Yb7k2tu1E97q3mm99t3s8UCGQ',
    appId: '1:141920116298:android:04ebf7fab9fe120ca3d0b3',
    messagingSenderId: '141920116298',
    projectId: 'growable-b7814',
    storageBucket: 'growable-b7814.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPUfHhMNZ8e11kiHp5P0takWYgA2F_aok',
    appId: '1:141920116298:ios:755b8c7365a19632a3d0b3',
    messagingSenderId: '141920116298',
    projectId: 'growable-b7814',
    storageBucket: 'growable-b7814.appspot.com',
    iosBundleId: 'com.example.growable',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPUfHhMNZ8e11kiHp5P0takWYgA2F_aok',
    appId: '1:141920116298:ios:88fe2ee7279e99aca3d0b3',
    messagingSenderId: '141920116298',
    projectId: 'growable-b7814',
    storageBucket: 'growable-b7814.appspot.com',
    iosBundleId: 'com.example.growable.RunnerTests',
  );
}
